In [6]:
import numpy as np

a = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])


2
6
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
a.ndim

2

In [8]:
a.size

6

In [9]:
a.shape

(2, 3)

In [10]:
np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
a = np.array([[1. ,2. ,3.], [4. ,5. ,6.]])
b = np.array([[2. ,2. ,3.], [4. ,5. ,6.]])
c = np.array([[3. ,2. ,3.], [4. ,5. ,6.]])
d = np.array([[4. ,2. ,3.], [4. ,5. ,6.]])

np.array([[1. ,2. ,3.], [4. ,5. ,6.]])

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
a[-1]

array([4., 5., 6.])

In [17]:
a = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10]])

a[1, 4]

10

In [18]:
a[1]

array([ 2,  4,  6,  8, 10])

In [32]:
a = np.random.rand(6, 10)

a

array([[0.95069923, 0.41075768, 0.48865895, 0.62020024, 0.31661063,
        0.69771285, 0.11846411, 0.01474717, 0.82394296, 0.50909523],
       [0.52838704, 0.16359355, 0.93645306, 0.32325223, 0.17694689,
        0.81792579, 0.41810173, 0.61302443, 0.23678572, 0.65450329],
       [0.33842844, 0.28900897, 0.26327879, 0.60366745, 0.36471573,
        0.44881662, 0.46687634, 0.26462234, 0.26538041, 0.24312154],
       [0.72298958, 0.40681417, 0.24091953, 0.75389511, 0.80451964,
        0.63318966, 0.71902374, 0.81543807, 0.85920083, 0.3689083 ],
       [0.50707254, 0.76293202, 0.64983414, 0.98571451, 0.30745892,
        0.67763991, 0.58369588, 0.44125704, 0.34990973, 0.66295651],
       [0.58900333, 0.91395689, 0.29843437, 0.70101837, 0.4279895 ,
        0.73616496, 0.11238111, 0.97149603, 0.76906579, 0.19035047]])

In [33]:
a[:5]

array([[0.95069923, 0.41075768, 0.48865895, 0.62020024, 0.31661063,
        0.69771285, 0.11846411, 0.01474717, 0.82394296, 0.50909523],
       [0.52838704, 0.16359355, 0.93645306, 0.32325223, 0.17694689,
        0.81792579, 0.41810173, 0.61302443, 0.23678572, 0.65450329],
       [0.33842844, 0.28900897, 0.26327879, 0.60366745, 0.36471573,
        0.44881662, 0.46687634, 0.26462234, 0.26538041, 0.24312154],
       [0.72298958, 0.40681417, 0.24091953, 0.75389511, 0.80451964,
        0.63318966, 0.71902374, 0.81543807, 0.85920083, 0.3689083 ],
       [0.50707254, 0.76293202, 0.64983414, 0.98571451, 0.30745892,
        0.67763991, 0.58369588, 0.44125704, 0.34990973, 0.66295651]])

In [36]:
a[-5:]

array([[0.52838704, 0.16359355, 0.93645306, 0.32325223, 0.17694689,
        0.81792579, 0.41810173, 0.61302443, 0.23678572, 0.65450329],
       [0.33842844, 0.28900897, 0.26327879, 0.60366745, 0.36471573,
        0.44881662, 0.46687634, 0.26462234, 0.26538041, 0.24312154],
       [0.72298958, 0.40681417, 0.24091953, 0.75389511, 0.80451964,
        0.63318966, 0.71902374, 0.81543807, 0.85920083, 0.3689083 ],
       [0.50707254, 0.76293202, 0.64983414, 0.98571451, 0.30745892,
        0.67763991, 0.58369588, 0.44125704, 0.34990973, 0.66295651],
       [0.58900333, 0.91395689, 0.29843437, 0.70101837, 0.4279895 ,
        0.73616496, 0.11238111, 0.97149603, 0.76906579, 0.19035047]])

In [35]:
a[0:3, 4:9]

array([[0.31661063, 0.69771285, 0.11846411, 0.01474717, 0.82394296],
       [0.17694689, 0.81792579, 0.41810173, 0.61302443, 0.23678572],
       [0.36471573, 0.44881662, 0.46687634, 0.26462234, 0.26538041]])

In [39]:
a[np.ix_([1, 3, 4], [0, 2])]

array([[0.52838704, 0.93645306],
       [0.72298958, 0.24091953],
       [0.50707254, 0.64983414]])

In [40]:
a[2:21:2,:]

array([[0.33842844, 0.28900897, 0.26327879, 0.60366745, 0.36471573,
        0.44881662, 0.46687634, 0.26462234, 0.26538041, 0.24312154],
       [0.50707254, 0.76293202, 0.64983414, 0.98571451, 0.30745892,
        0.67763991, 0.58369588, 0.44125704, 0.34990973, 0.66295651]])

In [41]:
a[ ::2,:]

array([[0.95069923, 0.41075768, 0.48865895, 0.62020024, 0.31661063,
        0.69771285, 0.11846411, 0.01474717, 0.82394296, 0.50909523],
       [0.33842844, 0.28900897, 0.26327879, 0.60366745, 0.36471573,
        0.44881662, 0.46687634, 0.26462234, 0.26538041, 0.24312154],
       [0.50707254, 0.76293202, 0.64983414, 0.98571451, 0.30745892,
        0.67763991, 0.58369588, 0.44125704, 0.34990973, 0.66295651]])

In [42]:
a[::-1,:]

array([[0.58900333, 0.91395689, 0.29843437, 0.70101837, 0.4279895 ,
        0.73616496, 0.11238111, 0.97149603, 0.76906579, 0.19035047],
       [0.50707254, 0.76293202, 0.64983414, 0.98571451, 0.30745892,
        0.67763991, 0.58369588, 0.44125704, 0.34990973, 0.66295651],
       [0.72298958, 0.40681417, 0.24091953, 0.75389511, 0.80451964,
        0.63318966, 0.71902374, 0.81543807, 0.85920083, 0.3689083 ],
       [0.33842844, 0.28900897, 0.26327879, 0.60366745, 0.36471573,
        0.44881662, 0.46687634, 0.26462234, 0.26538041, 0.24312154],
       [0.52838704, 0.16359355, 0.93645306, 0.32325223, 0.17694689,
        0.81792579, 0.41810173, 0.61302443, 0.23678572, 0.65450329],
       [0.95069923, 0.41075768, 0.48865895, 0.62020024, 0.31661063,
        0.69771285, 0.11846411, 0.01474717, 0.82394296, 0.50909523]])

In [43]:
a[np.r_[:len(a),0]]

array([[0.95069923, 0.41075768, 0.48865895, 0.62020024, 0.31661063,
        0.69771285, 0.11846411, 0.01474717, 0.82394296, 0.50909523],
       [0.52838704, 0.16359355, 0.93645306, 0.32325223, 0.17694689,
        0.81792579, 0.41810173, 0.61302443, 0.23678572, 0.65450329],
       [0.33842844, 0.28900897, 0.26327879, 0.60366745, 0.36471573,
        0.44881662, 0.46687634, 0.26462234, 0.26538041, 0.24312154],
       [0.72298958, 0.40681417, 0.24091953, 0.75389511, 0.80451964,
        0.63318966, 0.71902374, 0.81543807, 0.85920083, 0.3689083 ],
       [0.50707254, 0.76293202, 0.64983414, 0.98571451, 0.30745892,
        0.67763991, 0.58369588, 0.44125704, 0.34990973, 0.66295651],
       [0.58900333, 0.91395689, 0.29843437, 0.70101837, 0.4279895 ,
        0.73616496, 0.11238111, 0.97149603, 0.76906579, 0.19035047],
       [0.95069923, 0.41075768, 0.48865895, 0.62020024, 0.31661063,
        0.69771285, 0.11846411, 0.01474717, 0.82394296, 0.50909523]])

In [45]:
a.T

array([[0.95069923, 0.52838704, 0.33842844, 0.72298958, 0.50707254,
        0.58900333],
       [0.41075768, 0.16359355, 0.28900897, 0.40681417, 0.76293202,
        0.91395689],
       [0.48865895, 0.93645306, 0.26327879, 0.24091953, 0.64983414,
        0.29843437],
       [0.62020024, 0.32325223, 0.60366745, 0.75389511, 0.98571451,
        0.70101837],
       [0.31661063, 0.17694689, 0.36471573, 0.80451964, 0.30745892,
        0.4279895 ],
       [0.69771285, 0.81792579, 0.44881662, 0.63318966, 0.67763991,
        0.73616496],
       [0.11846411, 0.41810173, 0.46687634, 0.71902374, 0.58369588,
        0.11238111],
       [0.01474717, 0.61302443, 0.26462234, 0.81543807, 0.44125704,
        0.97149603],
       [0.82394296, 0.23678572, 0.26538041, 0.85920083, 0.34990973,
        0.76906579],
       [0.50909523, 0.65450329, 0.24312154, 0.3689083 , 0.66295651,
        0.19035047]])

In [46]:
a.conj().T

array([[0.95069923, 0.52838704, 0.33842844, 0.72298958, 0.50707254,
        0.58900333],
       [0.41075768, 0.16359355, 0.28900897, 0.40681417, 0.76293202,
        0.91395689],
       [0.48865895, 0.93645306, 0.26327879, 0.24091953, 0.64983414,
        0.29843437],
       [0.62020024, 0.32325223, 0.60366745, 0.75389511, 0.98571451,
        0.70101837],
       [0.31661063, 0.17694689, 0.36471573, 0.80451964, 0.30745892,
        0.4279895 ],
       [0.69771285, 0.81792579, 0.44881662, 0.63318966, 0.67763991,
        0.73616496],
       [0.11846411, 0.41810173, 0.46687634, 0.71902374, 0.58369588,
        0.11238111],
       [0.01474717, 0.61302443, 0.26462234, 0.81543807, 0.44125704,
        0.97149603],
       [0.82394296, 0.23678572, 0.26538041, 0.85920083, 0.34990973,
        0.76906579],
       [0.50909523, 0.65450329, 0.24312154, 0.3689083 , 0.66295651,
        0.19035047]])

In [55]:
a = np.random.randint(low=0, high=5, size = (2, 2))
b = np.random.randint(low=0, high=5, size = (2, 2))

print(a)
print(b)

[[3 3]
 [3 1]]
[[3 4]
 [3 2]]


In [57]:
a@b

array([[18, 18],
       [12, 14]])

In [58]:
a*b

array([[ 9, 12],
       [ 9,  2]])

In [59]:
a/b

array([[1.  , 0.75],
       [1.  , 0.5 ]])

In [60]:
a**3

array([[27, 27],
       [27,  1]])

In [61]:
a > 0.5

array([[ True,  True],
       [ True,  True]])

In [64]:
np.nonzero(a > 0.5)

(array([0, 0, 1, 1]), array([0, 1, 0, 1]))

In [66]:
a = np.random.rand(5, 5)
v = np.asarray([0, 1, 0.5, 1, 0.5])

print(a)

[[0.75765443 0.86593171 0.26507003 0.25257705 0.89902656]
 [0.12402521 0.21450254 0.35330044 0.02609244 0.84519803]
 [0.97617184 0.73484102 0.03183044 0.95909475 0.64450114]
 [0.51236307 0.21362919 0.90839932 0.11252498 0.66143677]
 [0.68005053 0.28786328 0.69409137 0.03104178 0.05888061]]


In [67]:
a[:,np.nonzero(v > 0.5)[0]]

array([[0.86593171, 0.25257705],
       [0.21450254, 0.02609244],
       [0.73484102, 0.95909475],
       [0.21362919, 0.11252498],
       [0.28786328, 0.03104178]])

In [68]:
a[:, v.T > 0.5]

array([[0.86593171, 0.25257705],
       [0.21450254, 0.02609244],
       [0.73484102, 0.95909475],
       [0.21362919, 0.11252498],
       [0.28786328, 0.03104178]])

In [70]:
a[a < 0.5]=0
a

array([[0.75765443, 0.86593171, 0.        , 0.        , 0.89902656],
       [0.        , 0.        , 0.        , 0.        , 0.84519803],
       [0.97617184, 0.73484102, 0.        , 0.95909475, 0.64450114],
       [0.51236307, 0.        , 0.90839932, 0.        , 0.66143677],
       [0.68005053, 0.        , 0.69409137, 0.        , 0.        ]])

In [71]:
a * (a > 0.5)
a

array([[0.75765443, 0.86593171, 0.        , 0.        , 0.89902656],
       [0.        , 0.        , 0.        , 0.        , 0.84519803],
       [0.97617184, 0.73484102, 0.        , 0.95909475, 0.64450114],
       [0.51236307, 0.        , 0.90839932, 0.        , 0.66143677],
       [0.68005053, 0.        , 0.69409137, 0.        , 0.        ]])

In [72]:
a[:] = 3
a

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [89]:
x = np.random.rand(3, 3)
y = x.copy()
y

array([[0.4514127 , 0.99234389, 0.87577318],
       [0.33985288, 0.97689215, 0.84746136],
       [0.34630321, 0.17046962, 0.16508755]])

In [90]:
x = np.random.randint(low=0, high=10, size = (5, 5))
y = x.copy()
y

array([[4, 1, 5, 7, 3],
       [0, 9, 9, 1, 9],
       [1, 1, 3, 9, 8],
       [7, 7, 1, 9, 3],
       [9, 7, 1, 2, 4]])

In [91]:
y = x[1, :].copy()
y

array([0, 9, 9, 1, 9])

In [92]:
y = x.flatten()
y

array([4, 1, 5, 7, 3, 0, 9, 9, 1, 9, 1, 1, 3, 9, 8, 7, 7, 1, 9, 3, 9, 7,
       1, 2, 4])

In [93]:
np.arange(1., 11.) 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [94]:
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [96]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [98]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
a = np.random.randint(low=0, high=10, size = (5, 5))
print(a)
np.diag(a)

[[6 1 3 8 3]
 [5 1 1 6 1]
 [8 7 5 5 4]
 [6 4 8 0 7]
 [1 1 9 3 6]]


array([6, 1, 5, 0, 6])

In [103]:
print(v)
np.diag(v, 0)

[0.  1.  0.5 1.  0.5]


array([[0. , 0. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. , 0. ],
       [0. , 0. , 0.5, 0. , 0. ],
       [0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 0.5]])

In [107]:
from numpy.random import default_rng
rng = default_rng(42)
rng.random((3, 4))

array([[0.77395605, 0.43887844, 0.85859792, 0.69736803],
       [0.09417735, 0.97562235, 0.7611397 , 0.78606431],
       [0.12811363, 0.45038594, 0.37079802, 0.92676499]])

In [108]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [109]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [111]:
np.ogrid[0:9.,0:6.]

[array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]), array([[0., 1., 2., 3., 4., 5.]])]

In [112]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]), array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [116]:
a = np.random.randint(low=0, high=10, size = (2, 2))
print(a)
np.tile(a, (3, 2))

[[7 1]
 [3 6]]


array([[7, 1, 7, 1],
       [3, 6, 3, 6],
       [7, 1, 7, 1],
       [3, 6, 3, 6],
       [7, 1, 7, 1],
       [3, 6, 3, 6]])

In [119]:
print(b)
np.hstack((a,b))

[[3 4]
 [3 2]]


array([[7, 1, 3, 4],
       [3, 6, 3, 2]])

In [120]:
np.vstack((a,b))

array([[7, 1],
       [3, 6],
       [3, 4],
       [3, 2]])

In [122]:
a.max() 

7

In [123]:
a.max(0)

array([7, 6])

In [124]:
np.maximum(a, b)

array([[7, 4],
       [3, 6]])

In [125]:
np.linalg.norm(v)

1.5811388300841898

In [127]:
np.logical_and(a,b)

array([[ True,  True],
       [ True,  True]])

In [128]:
np.logical_or(a,b)

array([[ True,  True],
       [ True,  True]])

In [129]:
a & b

array([[3, 0],
       [3, 2]])

In [130]:
a | b

array([[7, 5],
       [3, 6]])

In [132]:
np.linalg.inv(a)

array([[ 0.15384615, -0.02564103],
       [-0.07692308,  0.17948718]])

In [134]:
np.linalg.pinv(a)

array([[ 0.15384615, -0.02564103],
       [-0.07692308,  0.17948718]])

In [135]:
np.linalg.matrix_rank(a)

2

In [138]:
np.linalg.solve(a, b)

array([[0.38461538, 0.56410256],
       [0.30769231, 0.05128205]])

In [142]:
U, S, Vh = np.linalg.svd(a)
U, S, Vh

(array([[-0.73898519, -0.67372167],
        [-0.67372167,  0.73898519]]),
 array([8.63802603, 4.51492041]),
 array([[-0.83283626, -0.55351943],
        [-0.55351943,  0.83283626]]))

In [144]:
np.linalg.cholesky(a)

array([[2.64575131, 0.        ],
       [1.13389342, 2.17124059]])

In [145]:
np.linalg.eig(a)

(array([8.30277564, 4.69722436]), array([[ 0.60889368, -0.3983218 ],
        [ 0.79325185,  0.91724574]]))

In [147]:
np.linalg.eig((a, b))

(array([[ 8.30277564,  4.69722436],
        [ 6.        , -1.        ]]), array([[[ 0.60889368, -0.3983218 ],
         [ 0.79325185,  0.91724574]],
 
        [[ 0.8       , -0.70710678],
         [ 0.6       ,  0.70710678]]]))

In [151]:
from scipy.sparse.linalg import eigs
eigs(a, k = 3)

/usr/local/lib/python3.7/dist-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:1268: RuntimeWarning: k >= N - 1 for N * N square matrix. Attempting to use scipy.linalg.eig instead.
  RuntimeWarning)


(array([8.30277564+0.j, 4.69722436+0.j]), array([[ 0.60889368, -0.3983218 ],
        [ 0.79325185,  0.91724574]]))

In [152]:
np.linalg.qr(a)

(array([[-0.91914503, -0.3939193 ],
        [-0.3939193 ,  0.91914503]]), array([[-7.61577311, -3.28266082],
        [ 0.        ,  5.12095088]]))

In [156]:
from scipy.linalg import lu
lu(a)

(array([[1., 0.],
        [0., 1.]]), array([[1.        , 0.        ],
        [0.42857143, 1.        ]]), array([[7.        , 1.        ],
        [0.        , 5.57142857]]))

In [159]:
from scipy.sparse import csc_matrix
from scipy.sparse.linalg import cg

P = np.array([[4, 0, 1, 0],
                [0, 5, 0, 0],
                [1, 0, 3, 2],
                [0, 0, 2, 4]])
A = csc_matrix(P)
b = np.array([-1, -0.5, -1, 2])

cg(A, b)

(array([ 5.03611909e-17, -1.00000000e-01, -1.00000000e+00,  1.00000000e+00]),
 0)

In [162]:
np.fft.fft(a)

array([[ 8.+0.j,  6.+0.j],
       [ 9.+0.j, -3.+0.j]])

In [163]:
np.fft.ifft(a)

array([[ 4. +0.j,  3. +0.j],
       [ 4.5+0.j, -1.5+0.j]])

In [164]:
 np.sort(a) 

array([[1, 7],
       [3, 6]])

In [166]:
a.T
np.sort(a, axis = 1) 

array([[1, 7],
       [3, 6]])

In [169]:
I = np.argsort(a[:, 0]); b = a[I,:]
I

array([1, 0])

In [173]:
x = np.array([0, 1, 2, 3])
y = np.array([-1, 0.2, 0.9, 2.1])
A = np.vstack([x, np.ones(len(x))]).T
np.linalg.lstsq(A, y, rcond=None)[0]

array([ 1.  , -0.95])

In [179]:
from scipy import signal
x = np.linspace(0, 10, 20, endpoint=False)
y = np.cos(-x**2/6.0)
signal.resample(y, 100)

array([ 1.        ,  1.23283311,  1.31727019,  1.27302765,  1.14740269,
        0.99913207,  0.88078847,  0.82497964,  0.83806509,  0.90249922,
        0.98614323,  1.05486   ,  1.08402435,  1.06536954,  1.00747904,
        0.93050762,  0.85758366,  0.80620995,  0.78263328,  0.78081837,
        0.78588726,  0.78033048,  0.75048699,  0.69094819,  0.60552319,
        0.50478221,  0.40143727,  0.30548407,  0.22092394,  0.14511765,
        0.0707372 , -0.01068719, -0.10512733, -0.21370903, -0.33240564,
       -0.45366208, -0.56910426, -0.67215691, -0.75955883, -0.83131707,
       -0.88932657, -0.93540864, -0.9696874 , -0.98998822, -0.9924354 ,
       -0.97288395, -0.92847886, -0.85863231, -0.76502853, -0.65074937,
       -0.51903563, -0.37236513, -0.21236454, -0.04065068,  0.13978552,
        0.3233596 ,  0.50154373,  0.66375109,  0.79927642,  0.89960584,
        0.96017029,  0.98077748,  0.96447814,  0.91530208,  0.8358487 ,
        0.7258814 ,  0.58274561,  0.40370101,  0.18940426, -0.05

In [182]:
a = np.random.randint(low=0, high=6, size = (5, 5))
np.unique(a)

array([0, 1, 2, 3, 4, 5])

In [188]:
x = np.array([[[0], [1], [2]]])
print(x)
np.squeeze(x)

[[[0]
  [1]
  [2]]]


array([0, 1, 2])